AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Prod
    Variables:
        ServerlessExpressLambdaFunctionName: !Ref LambdaRead

  myDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: tabmine
      PrimaryKey:
        Name: Title
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 

  
  LambdaWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionWrite/
      Handler: write.handler
      Runtime: python3.8
      Timeout: 100
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /writedb
            Method: post
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref myDB
            
  LambdaRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionRead/
      Handler: read.handler
      Runtime: python3.8
      Timeout: 100
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /readdb
            Method: post
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref myDB

Outputs:
  BasicAWSApiGateway:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "http://127.0.0.1/Prod/"